[build]
  command = "pip install -r requirements.txt"
  publish = "."          # Publish from the root directory
  functions = ".netlify/functions"  # Correct path to Netlify Functions

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true