[build]
  command = "npm install && pip install -r requirements.txt"
  publish = "."
  functions = ".netlify/functions"

[[redirects]]
  from = "/api/convert_time"
  to = "/.netlify/functions/convert_time"
  status = 200
  force = true

[[redirects]]
  from = "/api/save_cart"
  to = "/.netlify/functions/save_cart"
  status = 200
  force = true

[[redirects]]
  from = "/api/get_cart"
  to = "/.netlify/functions/get_cart"
  status = 200
  force = true

# Handle OPTIONS preflight requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"