[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = ".netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true